using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyWindowsMediaPlayer.Model;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;

namespace UnitTestMyWindowsMediaPlayer
{
    [TestClass]
    public class TestXmlBDD
    {
        [TestMethod]
        [Timeout(1000)]
        public void InstanciateXmlBDD()
        {
            IBDD idd = new XmlBDD();
        }
        [TestMethod]
        [Timeout(1000)]
        public void InstanciateXmlBDDWithGoodPath()
        {
            IBDD idd = new XmlBDD("ramdom.xml");
        }
        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(ArgumentException))]
        public void InstanciateXmlBDDWithWrongPath()
        {
            IBDD idd = new XmlBDD("");
        }
        [TestMethod]
        [Timeout(1000)]
        public void AddListMedia()
        {
            String path = "42.xml";
            System.IO.File.Delete(path);
            IBDD ibdd = new XmlBDD(path);
            var mediaList = new List<String>();

            foreach (var i in Enumerable.Range(0, 42))
                mediaList.Add(i.ToString());
            ibdd.AddMedia(mediaList, "the answer to life the universe and everything");
            ibdd.Flush();
            var result = System.IO.File.ReadAllText(System.IO.Path.GetFullPath(path));
            #region expectedResult
            String expectedResult = @"<?xml version=""1.0""?>
<Xml xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <MediaList>
    <Media>
      <Id>0</Id>
      <Path>0</Path>
    </Media>
    <Media>
      <Id>1</Id>
      <Path>1</Path>
    </Media>
    <Media>
      <Id>2</Id>
      <Path>2</Path>
    </Media>
    <Media>
      <Id>3</Id>
      <Path>3</Path>
    </Media>
    <Media>
      <Id>4</Id>
      <Path>4</Path>
    </Media>
    <Media>
      <Id>5</Id>
      <Path>5</Path>
    </Media>
    <Media>
      <Id>6</Id>
      <Path>6</Path>
    </Media>
    <Media>
      <Id>7</Id>
      <Path>7</Path>
    </Media>
    <Media>
      <Id>8</Id>
      <Path>8</Path>
    </Media>
    <Media>
      <Id>9</Id>
      <Path>9</Path>
    </Media>
    <Media>
      <Id>10</Id>
      <Path>10</Path>
    </Media>
    <Media>
      <Id>11</Id>
      <Path>11</Path>
    </Media>
    <Media>
      <Id>12</Id>
      <Path>12</Path>
    </Media>
    <Media>
      <Id>13</Id>
      <Path>13</Path>
    </Media>
    <Media>
      <Id>14</Id>
      <Path>14</Path>
    </Media>
    <Media>
      <Id>15</Id>
      <Path>15</Path>
    </Media>
    <Media>
      <Id>16</Id>
      <Path>16</Path>
    </Media>
    <Media>
      <Id>17</Id>
      <Path>17</Path>
    </Media>
    <Media>
      <Id>18</Id>
      <Path>18</Path>
    </Media>
    <Media>
      <Id>19</Id>
      <Path>19</Path>
    </Media>
    <Media>
      <Id>20</Id>
      <Path>20</Path>
    </Media>
    <Media>
      <Id>21</Id>
      <Path>21</Path>
    </Media>
    <Media>
      <Id>22</Id>
      <Path>22</Path>
    </Media>
    <Media>
      <Id>23</Id>
      <Path>23</Path>
    </Media>
    <Media>
      <Id>24</Id>
      <Path>24</Path>
    </Media>
    <Media>
      <Id>25</Id>
      <Path>25</Path>
    </Media>
    <Media>
      <Id>26</Id>
      <Path>26</Path>
    </Media>
    <Media>
      <Id>27</Id>
      <Path>27</Path>
    </Media>
    <Media>
      <Id>28</Id>
      <Path>28</Path>
    </Media>
    <Media>
      <Id>29</Id>
      <Path>29</Path>
    </Media>
    <Media>
      <Id>30</Id>
      <Path>30</Path>
    </Media>
    <Media>
      <Id>31</Id>
      <Path>31</Path>
    </Media>
    <Media>
      <Id>32</Id>
      <Path>32</Path>
    </Media>
    <Media>
      <Id>33</Id>
      <Path>33</Path>
    </Media>
    <Media>
      <Id>34</Id>
      <Path>34</Path>
    </Media>
    <Media>
      <Id>35</Id>
      <Path>35</Path>
    </Media>
    <Media>
      <Id>36</Id>
      <Path>36</Path>
    </Media>
    <Media>
      <Id>37</Id>
      <Path>37</Path>
    </Media>
    <Media>
      <Id>38</Id>
      <Path>38</Path>
    </Media>
    <Media>
      <Id>39</Id>
      <Path>39</Path>
    </Media>
    <Media>
      <Id>40</Id>
      <Path>40</Path>
    </Media>
    <Media>
      <Id>41</Id>
      <Path>41</Path>
    </Media>
  </MediaList>
  <PlaylistList>
    <Playlist>
      <Id>0</Id>
      <Name>the answer to life the universe and everything</Name>
    </Playlist>
  </PlaylistList>
  <LinkList>
    <Link>
      <IdMedia>0</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>1</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>2</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>3</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>4</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>5</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>6</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>7</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>8</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>9</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>10</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>11</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>12</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>13</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>14</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>15</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>16</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>17</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>18</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>19</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>20</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>21</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>22</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>23</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>24</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>25</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>26</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>27</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>28</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>29</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>30</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>31</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>32</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>33</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>34</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>35</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>36</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>37</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>38</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>39</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>40</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
    <Link>
      <IdMedia>41</IdMedia>
      <IdPlaylist>0</IdPlaylist>
    </Link>
  </LinkList>
</Xml>";
            #endregion
            Assert.AreEqual(expectedResult, result);
        }
    }
}
